spring:
  application:
    name: springcloud-zuul-service
server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    #  # routes to serviceId
    springcloud-provider-service:
      path: /springcloud-provider-service/**
      serviceId: springcloud-provider-service
    springcloud-order-service:
      path: /springcloud-order-service/**
      serviceId: springcloud-order-service
    #  # routes to url
    springcloud-provider-service-url:
      path: /springcloud-provider-service-url/**
      url: http://localhost:9000/
    springcloud-order-service-url:
      path: /springcloud-order-service-url/**
      url: http://localhost:9100/