#服务端口号
server:
  port: 9100
  ###服务名称 --注册到注册中心的服务名称
spring:
  application:
    name: springcloud-order-service

###eureka基本配置信息
eureka:
  client:
    service-url:
      ####当前服务的注册中心地址
      defaultZone: http://localhost:8000/eureka
      ###需要将服务注册到eureka上
    register-with-eureka: true
    #####需要去检索服务信息
    fetch-registry: true
  instance:
    #    lease-renewal-interval-in-seconds、expiration-duration-in-seconds 这两个是自己设置的轮询时间，上面的50和30是在实际项目中设置的值，如果不设置系统有默认值。
    lease-renewal-interval-in-seconds: 50
    lease-expiration-duration-in-seconds: 30
